# Generated by Django 4.1.5 on 2023-01-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_tag_alter_category_options_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, to="blog.tag"),
        ),
    ]
