# Generated by Django 4.1.5 on 2023-01-18 17:16

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=markdownx.models.MarkdownxField(),
        ),
    ]
